# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Learning-WkWebView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleAPIClientForREST/Drive', '~> 1.2.1'
  pod 'GoogleSignIn', '~> 4.1.1'

  # Pods for Learning-WkWebView

end
